name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ec5f14e7-3500-42c5-97e0-38a22d42a839
      AZURE_CLIENT_SECRET: Wat8Q~PhB39vpqbgmc365uWQrclZP5b5WBYWZbRC
      AZURE_TENANT_ID: ce6d1ef4-a8d0-42a6-8b71-a3630c44e6db
      AZURE_SUBSCRIPTION_ID: 809b4f5a-970c-49bd-b1d5-cec8c691c6f1
      AZURE_RESOURCE_GROUP_NAME: qwerty123452
      AZURE_FUNCTION_NAME: qwerty12345

    steps:
      - name: Echo Azure Credentials
        run: |
          echo "Azure Client ID: $AZURE_CLIENT_ID"
          echo "Azure Client Secret: $AZURE_CLIENT_SECRET"
          echo "Azure Tenant ID: $AZURE_TENANT_ID"
          echo "Azure Subscription ID: $AZURE_SUBSCRIPTION_ID"

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test
        
      - name: Azure Login
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - name: Deploy to Azure Function App
        run: |
          # Build and package your Django application for deployment
          az functionapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP_NAME --name $AZURE_FUNCTION_NAME --src ./project1.zip --build-remote true
          az functionapp restart --resource-group $AZURE_RESOURCE_GROUP_NAME --name $AZURE_FUNCTION_NAME
