name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ec5f14e7-3500-42c5-97e0-38a22d42a839
      AZURE_CLIENT_SECRET: Wat8Q~PhB39vpqbgmc365uWQrclZP5b5WBYWZbRC
      AZURE_TENANT_ID: ce6d1ef4-a8d0-42a6-8b71-a3630c44e6db
      AZURE_SUBSCRIPTION_ID: 809b4f5a-970c-49bd-b1d5-cec8c691c6f1
      AZURE_RESOURCE_GROUP_NAME: qwerty123452
      AZURE_FUNCTION_NAME: qwerty12345
      DOCKER_USERNAME: rubanbharath14@gmail.com
      DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
      DOCKER_NAME: ruban14
      DOCKER_IMAGE_NAME: project1
      DOCKER_TAG: latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_SECRET }} | docker login -u rubanbharath14@gmail.com --password-stdin
      
      - name: Pull Docker Image
        run: |
          docker pull $DOCKER_NAME/$DOCKER_IMAGE_NAME

      - name: Deploy to Azure Functions
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az functionapp config container set --name $AZURE_FUNCTION_NAME --resource-group $AZURE_RESOURCE_GROUP_NAME --docker-custom-image-name $DOCKER_NAME/$DOCKER_IMAGE_NAME
          
      - name: Azure Restart
        run: |
          az functionapp restart --resource-group $AZURE_RESOURCE_GROUP_NAME --name $AZURE_FUNCTION_NAME